// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gin-crud-api/internal/ent/employee"
	"gin-crud-api/internal/ent/predicate"
	"gin-crud-api/internal/ent/project"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdate) ClearDescription() *ProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectUpdate) SetStatus(v project.Status) *ProjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableStatus(v *project.Status) *ProjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProjectUpdate) SetPriority(v project.Priority) *ProjectUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillablePriority(v *project.Priority) *ProjectUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectUpdate) SetStartDate(v time.Time) *ProjectUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableStartDate(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectUpdate) SetEndDate(v time.Time) *ProjectUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEndDate(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetBudget sets the "budget" field.
func (_u *ProjectUpdate) SetBudget(v float64) *ProjectUpdate {
	_u.mutation.ResetBudget()
	_u.mutation.SetBudget(v)
	return _u
}

// SetNillableBudget sets the "budget" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableBudget(v *float64) *ProjectUpdate {
	if v != nil {
		_u.SetBudget(*v)
	}
	return _u
}

// AddBudget adds value to the "budget" field.
func (_u *ProjectUpdate) AddBudget(v float64) *ProjectUpdate {
	_u.mutation.AddBudget(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTeamMemberIDs adds the "team_members" edge to the Employee entity by IDs.
func (_u *ProjectUpdate) AddTeamMemberIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddTeamMemberIDs(ids...)
	return _u
}

// AddTeamMembers adds the "team_members" edges to the Employee entity.
func (_u *ProjectUpdate) AddTeamMembers(v ...*Employee) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamMemberIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTeamMembers clears all "team_members" edges to the Employee entity.
func (_u *ProjectUpdate) ClearTeamMembers() *ProjectUpdate {
	_u.mutation.ClearTeamMembers()
	return _u
}

// RemoveTeamMemberIDs removes the "team_members" edge to Employee entities by IDs.
func (_u *ProjectUpdate) RemoveTeamMemberIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveTeamMemberIDs(ids...)
	return _u
}

// RemoveTeamMembers removes "team_members" edges to Employee entities.
func (_u *ProjectUpdate) RemoveTeamMembers(v ...*Employee) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := project.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Project.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Budget(); ok {
		if err := project.BudgetValidator(v); err != nil {
			return &ValidationError{Name: "budget", err: fmt.Errorf(`ent: validator failed for field "Project.budget": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(project.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Budget(); ok {
		_spec.SetField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBudget(); ok {
		_spec.AddField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamMembersIDs(); len(nodes) > 0 && !_u.mutation.TeamMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProjectUpdateOne) SetStatus(v project.Status) *ProjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableStatus(v *project.Status) *ProjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProjectUpdateOne) SetPriority(v project.Priority) *ProjectUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillablePriority(v *project.Priority) *ProjectUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProjectUpdateOne) SetStartDate(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableStartDate(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProjectUpdateOne) SetEndDate(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEndDate(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetBudget sets the "budget" field.
func (_u *ProjectUpdateOne) SetBudget(v float64) *ProjectUpdateOne {
	_u.mutation.ResetBudget()
	_u.mutation.SetBudget(v)
	return _u
}

// SetNillableBudget sets the "budget" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableBudget(v *float64) *ProjectUpdateOne {
	if v != nil {
		_u.SetBudget(*v)
	}
	return _u
}

// AddBudget adds value to the "budget" field.
func (_u *ProjectUpdateOne) AddBudget(v float64) *ProjectUpdateOne {
	_u.mutation.AddBudget(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTeamMemberIDs adds the "team_members" edge to the Employee entity by IDs.
func (_u *ProjectUpdateOne) AddTeamMemberIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddTeamMemberIDs(ids...)
	return _u
}

// AddTeamMembers adds the "team_members" edges to the Employee entity.
func (_u *ProjectUpdateOne) AddTeamMembers(v ...*Employee) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamMemberIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearTeamMembers clears all "team_members" edges to the Employee entity.
func (_u *ProjectUpdateOne) ClearTeamMembers() *ProjectUpdateOne {
	_u.mutation.ClearTeamMembers()
	return _u
}

// RemoveTeamMemberIDs removes the "team_members" edge to Employee entities by IDs.
func (_u *ProjectUpdateOne) RemoveTeamMemberIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveTeamMemberIDs(ids...)
	return _u
}

// RemoveTeamMembers removes "team_members" edges to Employee entities.
func (_u *ProjectUpdateOne) RemoveTeamMembers(v ...*Employee) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamMemberIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := project.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Project.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := project.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Project.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Budget(); ok {
		if err := project.BudgetValidator(v); err != nil {
			return &ValidationError{Name: "budget", err: fmt.Errorf(`ent: validator failed for field "Project.budget": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(project.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(project.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Budget(); ok {
		_spec.SetField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBudget(); ok {
		_spec.AddField(project.FieldBudget, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamMembersIDs(); len(nodes) > 0 && !_u.mutation.TeamMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.TeamMembersTable,
			Columns: project.TeamMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
