// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Input for creating a new department
type CreateDepartmentInput struct {
	// Department name (required)
	Name string `json:"name"`
}

// Input for creating a new employee
type CreateEmployeeInput struct {
	// Employee full name (required)
	Name string `json:"name"`
	// Employee email address (required, must be unique and valid email format)
	Email string `json:"email"`
	// ID of the department (required, must reference an existing department)
	DepartmentID string `json:"departmentID"`
}

// Department represents an organizational department.
// Each department can have multiple employees.
type Department struct {
	// Unique identifier (UUID)
	ID string `json:"id"`
	// Department name
	Name string `json:"name"`
	// List of employees in this department
	Employees []*Employee `json:"employees,omitempty"`
}

// Employee represents a person working in a department.
// Each employee must belong to exactly one department.
type Employee struct {
	// Unique identifier (UUID)
	ID string `json:"id"`
	// Employee full name
	Name string `json:"name"`
	// Employee email address (must be unique)
	Email string `json:"email"`
	// ID of the department this employee belongs to
	DepartmentID string `json:"departmentID"`
	// The department this employee belongs to
	Department *Department `json:"department,omitempty"`
}

// Mutation root type - All mutations extend this type
type Mutation struct {
}

// Query root type - All queries extend this type
type Query struct {
}

// Input for updating an existing department
type UpdateDepartmentInput struct {
	// Department name (required)
	Name string `json:"name"`
}

// Input for updating an existing employee
type UpdateEmployeeInput struct {
	// Employee full name (required)
	Name string `json:"name"`
	// Employee email address (required, must be unique and valid email format)
	Email string `json:"email"`
	// ID of the department (required, must reference an existing department)
	DepartmentID string `json:"departmentID"`
}
