package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"
	"fmt"
	"gin-crud-api/internal/database"
	"gin-crud-api/internal/graph/model"
	"gin-crud-api/internal/logger"
	"gin-crud-api/internal/middleware"

	"github.com/google/uuid"
)

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.CreateEmployeeInput) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "createEmployee").
		Str("name", input.Name).
		Str("email", input.Email).
		Str("department_id", input.DepartmentID).
		Msg("Creating employee")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: employee name is required")
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: employee email is required")
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		log.Error().
			Str("operation", "createEmployee").
			Str("email", input.Email).
			Msg("Validation failed: invalid email format")
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: department ID is required")
		return nil, errors.New("department ID is required")
	}

	// Verify department exists
	_, err := r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, database.ErrNotFound) {
			log.Warn().
				Str("operation", "createEmployee").
				Str("department_id", input.DepartmentID).
				Msg("Department not found")
			return nil, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "createEmployee").
			Str("department_id", input.DepartmentID).
			Msg("Failed to verify department")
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Create GraphQL model
	emp := &model.Employee{
		ID:           uuid.New().String(),
		Name:         input.Name,
		Email:        input.Email,
		DepartmentID: input.DepartmentID,
	}

	// Save to repository
	if err := r.EmpRepo.Save(emp); err != nil {
		log.Error().
			Err(err).
			Str("operation", "createEmployee").
			Str("employee_id", emp.ID).
			Msg("Failed to save employee")
		return nil, fmt.Errorf("failed to create employee: %w", err)
	}

	log.Info().
		Str("operation", "createEmployee").
		Str("employee_id", emp.ID).
		Str("name", emp.Name).
		Str("email", emp.Email).
		Str("department_id", emp.DepartmentID).
		Msg("Employee created successfully")

	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, id string, input model.UpdateEmployeeInput) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "updateEmployee").
		Str("employee_id", id).
		Str("new_name", input.Name).
		Str("new_email", input.Email).
		Str("new_department_id", input.DepartmentID).
		Msg("Updating employee")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: employee name is required")
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: employee email is required")
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Str("email", input.Email).
			Msg("Validation failed: invalid email format")
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: department ID is required")
		return nil, errors.New("department ID is required")
	}

	// Check if employee exists
	existing, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, database.ErrNotFound) {
			log.Warn().
				Str("operation", "updateEmployee").
				Str("employee_id", id).
				Msg("Employee not found")
			return nil, fmt.Errorf("employee not found")
		}
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	// Verify department exists
	_, err = r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, database.ErrNotFound) {
			log.Warn().
				Str("operation", "updateEmployee").
				Str("employee_id", id).
				Str("department_id", input.DepartmentID).
				Msg("Department not found")
			return nil, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Str("department_id", input.DepartmentID).
			Msg("Failed to verify department")
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Update GraphQL model
	existing.Name = input.Name
	existing.Email = input.Email
	existing.DepartmentID = input.DepartmentID

	// Save to repository
	if err := r.EmpRepo.Update(existing); err != nil {
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Failed to update employee")
		return nil, fmt.Errorf("failed to update employee: %w", err)
	}

	log.Info().
		Str("operation", "updateEmployee").
		Str("employee_id", existing.ID).
		Str("name", existing.Name).
		Str("email", existing.Email).
		Str("department_id", existing.DepartmentID).
		Msg("Employee updated successfully")

	return &model.Employee{
		ID:           existing.ID,
		Name:         existing.Name,
		Email:        existing.Email,
		DepartmentID: existing.DepartmentID,
	}, nil
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *mutationResolver) DeleteEmployee(ctx context.Context, id string) (bool, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "deleteEmployee").
		Str("employee_id", id).
		Msg("Deleting employee")

	// Check if employee exists
	_, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, database.ErrNotFound) {
			log.Warn().
				Str("operation", "deleteEmployee").
				Str("employee_id", id).
				Msg("Employee not found")
			return false, fmt.Errorf("employee not found")
		}
		log.Error().
			Err(err).
			Str("operation", "deleteEmployee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return false, fmt.Errorf("failed to find employee: %w", err)
	}

	// Delete the employee
	if err := r.EmpRepo.Delete(id); err != nil {
		log.Error().
			Err(err).
			Str("operation", "deleteEmployee").
			Str("employee_id", id).
			Msg("Failed to delete employee")
		return false, fmt.Errorf("failed to delete employee: %w", err)
	}

	log.Info().
		Str("operation", "deleteEmployee").
		Str("employee_id", id).
		Msg("Employee deleted successfully")

	return true, nil
}

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id string) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employee").
		Str("employee_id", id).
		Msg("Fetching employee")

	emp, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, database.ErrNotFound) {
			log.Debug().
				Str("operation", "employee").
				Str("employee_id", id).
				Msg("Employee not found")
			return nil, nil // GraphQL convention: return nil for not found
		}
		log.Error().
			Err(err).
			Str("operation", "employee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	log.Debug().
		Str("operation", "employee").
		Str("employee_id", emp.ID).
		Str("name", emp.Name).
		Msg("Employee found")

	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context) ([]*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employees").
		Msg("Fetching all employees")

	emps, err := r.EmpRepo.FindAll()
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "employees").
			Msg("Failed to fetch employees")
		return nil, fmt.Errorf("failed to fetch employees: %w", err)
	}

	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	log.Debug().
		Str("operation", "employees").
		Int("count", len(result)).
		Msg("Employees fetched successfully")

	return result, nil
}

// EmployeesByDepartment is the resolver for the employeesByDepartment field.
func (r *queryResolver) EmployeesByDepartment(ctx context.Context, departmentID string) ([]*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employeesByDepartment").
		Str("department_id", departmentID).
		Msg("Fetching employees by department")

	emps, err := r.EmpRepo.FindByDepartmentID(departmentID)
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "employeesByDepartment").
			Str("department_id", departmentID).
			Msg("Failed to fetch employees by department")
		return nil, fmt.Errorf("failed to fetch employees by department: %w", err)
	}

	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	log.Debug().
		Str("operation", "employeesByDepartment").
		Str("department_id", departmentID).
		Int("count", len(result)).
		Msg("Employees fetched successfully")

	return result, nil
}
