package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"
	"fmt"
	"gin-crud-api/internal/graph/model"
	"gin-crud-api/internal/models"
	"regexp"

	"github.com/google/uuid"
)

// ============================================================================
// Mutation Resolvers - Department
// ============================================================================

// CreateDepartment is the resolver for the createDepartment field.
func (r *mutationResolver) CreateDepartment(ctx context.Context, input model.CreateDepartmentInput) (*model.Department, error) {
	// Validate input
	if input.Name == "" {
		return nil, errors.New("department name is required")
	}

	// Create domain model
	dept := &models.Department{
		ID:   uuid.New().String(),
		Name: input.Name,
	}

	// Save to repository
	if err := r.DeptRepo.Save(dept); err != nil {
		return nil, fmt.Errorf("failed to create department: %w", err)
	}

	// Convert to GraphQL model
	return &model.Department{
		ID:   dept.ID,
		Name: dept.Name,
	}, nil
}

// UpdateDepartment is the resolver for the updateDepartment field.
func (r *mutationResolver) UpdateDepartment(ctx context.Context, id string, input model.UpdateDepartmentInput) (*model.Department, error) {
	// Validate input
	if input.Name == "" {
		return nil, errors.New("department name is required")
	}

	// Check if department exists
	existing, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, fmt.Errorf("department not found")
		}
		return nil, fmt.Errorf("failed to find department: %w", err)
	}

	// Update domain model
	existing.Name = input.Name

	// Save to repository
	if err := r.DeptRepo.Update(existing); err != nil {
		return nil, fmt.Errorf("failed to update department: %w", err)
	}

	// Convert to GraphQL model
	return &model.Department{
		ID:   existing.ID,
		Name: existing.Name,
	}, nil
}

// DeleteDepartment is the resolver for the deleteDepartment field.
func (r *mutationResolver) DeleteDepartment(ctx context.Context, id string) (bool, error) {
	// Check if department exists
	_, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return false, fmt.Errorf("department not found")
		}
		return false, fmt.Errorf("failed to find department: %w", err)
	}

	// Cascade delete: delete all employees in this department
	employees, err := r.EmpRepo.FindByDepartmentID(id)
	if err != nil {
		return false, fmt.Errorf("failed to find employees: %w", err)
	}

	for _, emp := range employees {
		if err := r.EmpRepo.Delete(emp.ID); err != nil {
			return false, fmt.Errorf("failed to delete employee %s: %w", emp.ID, err)
		}
	}

	// Delete the department
	if err := r.DeptRepo.Delete(id); err != nil {
		return false, fmt.Errorf("failed to delete department: %w", err)
	}

	return true, nil
}

// ============================================================================
// Mutation Resolvers - Employee
// ============================================================================

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.CreateEmployeeInput) (*model.Employee, error) {
	// Validate input
	if input.Name == "" {
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		return nil, errors.New("department ID is required")
	}

	// Verify department exists
	_, err := r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, fmt.Errorf("department not found")
		}
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Create domain model
	emp := &models.Employee{
		ID:           uuid.New().String(),
		Name:         input.Name,
		Email:        input.Email,
		DepartmentID: input.DepartmentID,
	}

	// Save to repository
	if err := r.EmpRepo.Save(emp); err != nil {
		return nil, fmt.Errorf("failed to create employee: %w", err)
	}

	// Convert to GraphQL model
	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, id string, input model.UpdateEmployeeInput) (*model.Employee, error) {
	// Validate input
	if input.Name == "" {
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		return nil, errors.New("department ID is required")
	}

	// Check if employee exists
	existing, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, fmt.Errorf("employee not found")
		}
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	// Verify department exists
	_, err = r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, fmt.Errorf("department not found")
		}
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Update domain model
	existing.Name = input.Name
	existing.Email = input.Email
	existing.DepartmentID = input.DepartmentID

	// Save to repository
	if err := r.EmpRepo.Update(existing); err != nil {
		return nil, fmt.Errorf("failed to update employee: %w", err)
	}

	// Convert to GraphQL model
	return &model.Employee{
		ID:           existing.ID,
		Name:         existing.Name,
		Email:        existing.Email,
		DepartmentID: existing.DepartmentID,
	}, nil
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *mutationResolver) DeleteEmployee(ctx context.Context, id string) (bool, error) {
	// Check if employee exists
	_, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return false, fmt.Errorf("employee not found")
		}
		return false, fmt.Errorf("failed to find employee: %w", err)
	}

	// Delete the employee
	if err := r.EmpRepo.Delete(id); err != nil {
		return false, fmt.Errorf("failed to delete employee: %w", err)
	}

	return true, nil
}

// ============================================================================
// Query Resolvers - Department
// ============================================================================

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context, id string) (*model.Department, error) {
	dept, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, nil // GraphQL convention: return nil for not found
		}
		return nil, fmt.Errorf("failed to find department: %w", err)
	}

	return &model.Department{
		ID:   dept.ID,
		Name: dept.Name,
	}, nil
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	depts, err := r.DeptRepo.FindAll()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch departments: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Department, len(depts))
	for i, dept := range depts {
		result[i] = &model.Department{
			ID:   dept.ID,
			Name: dept.Name,
		}
	}

	return result, nil
}

// ============================================================================
// Query Resolvers - Employee
// ============================================================================

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id string) (*model.Employee, error) {
	emp, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			return nil, nil // GraphQL convention: return nil for not found
		}
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context) ([]*model.Employee, error) {
	emps, err := r.EmpRepo.FindAll()
	if err != nil {
		return nil, fmt.Errorf("failed to fetch employees: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	return result, nil
}

// EmployeesByDepartment is the resolver for the employeesByDepartment field.
func (r *queryResolver) EmployeesByDepartment(ctx context.Context, departmentID string) ([]*model.Employee, error) {
	emps, err := r.EmpRepo.FindByDepartmentID(departmentID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch employees by department: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	return result, nil
}

// ============================================================================
// Query Resolvers - Health Check
// ============================================================================

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// ============================================================================
// Helper Functions
// ============================================================================

// isValidEmail validates email format
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
