package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"errors"
	"fmt"
	"gin-crud-api/internal/graph/model"
	"gin-crud-api/internal/logger"
	"gin-crud-api/internal/middleware"
	"gin-crud-api/internal/models"
	"regexp"

	"github.com/google/uuid"
)

// ============================================================================
// Mutation Resolvers - Department
// ============================================================================

// CreateDepartment is the resolver for the createDepartment field.
func (r *mutationResolver) CreateDepartment(ctx context.Context, input model.CreateDepartmentInput) (*model.Department, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "createDepartment").
		Str("name", input.Name).
		Msg("Creating department")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "createDepartment").
			Msg("Validation failed: department name is required")
		return nil, errors.New("department name is required")
	}

	// Create domain model
	dept := &models.Department{
		ID:   uuid.New().String(),
		Name: input.Name,
	}

	// Save to repository
	if err := r.DeptRepo.Save(dept); err != nil {
		log.Error().
			Err(err).
			Str("operation", "createDepartment").
			Str("department_id", dept.ID).
			Msg("Failed to save department")
		return nil, fmt.Errorf("failed to create department: %w", err)
	}

	log.Info().
		Str("operation", "createDepartment").
		Str("department_id", dept.ID).
		Str("name", dept.Name).
		Msg("Department created successfully")

	// Convert to GraphQL model
	return &model.Department{
		ID:   dept.ID,
		Name: dept.Name,
	}, nil
}

// UpdateDepartment is the resolver for the updateDepartment field.
func (r *mutationResolver) UpdateDepartment(ctx context.Context, id string, input model.UpdateDepartmentInput) (*model.Department, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "updateDepartment").
		Str("department_id", id).
		Str("new_name", input.Name).
		Msg("Updating department")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "updateDepartment").
			Str("department_id", id).
			Msg("Validation failed: department name is required")
		return nil, errors.New("department name is required")
	}

	// Check if department exists
	existing, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "updateDepartment").
				Str("department_id", id).
				Msg("Department not found")
			return nil, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "updateDepartment").
			Str("department_id", id).
			Msg("Failed to find department")
		return nil, fmt.Errorf("failed to find department: %w", err)
	}

	// Update domain model
	existing.Name = input.Name

	// Save to repository
	if err := r.DeptRepo.Update(existing); err != nil {
		log.Error().
			Err(err).
			Str("operation", "updateDepartment").
			Str("department_id", id).
			Msg("Failed to update department")
		return nil, fmt.Errorf("failed to update department: %w", err)
	}

	log.Info().
		Str("operation", "updateDepartment").
		Str("department_id", existing.ID).
		Str("name", existing.Name).
		Msg("Department updated successfully")

	// Convert to GraphQL model
	return &model.Department{
		ID:   existing.ID,
		Name: existing.Name,
	}, nil
}

// DeleteDepartment is the resolver for the deleteDepartment field.
func (r *mutationResolver) DeleteDepartment(ctx context.Context, id string) (bool, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "deleteDepartment").
		Str("department_id", id).
		Msg("Deleting department with cascade")

	// Check if department exists
	_, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "deleteDepartment").
				Str("department_id", id).
				Msg("Department not found")
			return false, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "deleteDepartment").
			Str("department_id", id).
			Msg("Failed to find department")
		return false, fmt.Errorf("failed to find department: %w", err)
	}

	// Cascade delete: delete all employees in this department
	employees, err := r.EmpRepo.FindByDepartmentID(id)
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "deleteDepartment").
			Str("department_id", id).
			Msg("Failed to find employees for cascade delete")
		return false, fmt.Errorf("failed to find employees: %w", err)
	}

	log.Info().
		Str("operation", "deleteDepartment").
		Str("department_id", id).
		Int("employee_count", len(employees)).
		Msg("Cascade deleting employees")

	for _, emp := range employees {
		if err := r.EmpRepo.Delete(emp.ID); err != nil {
			log.Error().
				Err(err).
				Str("operation", "deleteDepartment").
				Str("department_id", id).
				Str("employee_id", emp.ID).
				Msg("Failed to delete employee during cascade")
			return false, fmt.Errorf("failed to delete employee %s: %w", emp.ID, err)
		}
	}

	// Delete the department
	if err := r.DeptRepo.Delete(id); err != nil {
		log.Error().
			Err(err).
			Str("operation", "deleteDepartment").
			Str("department_id", id).
			Msg("Failed to delete department")
		return false, fmt.Errorf("failed to delete department: %w", err)
	}

	log.Info().
		Str("operation", "deleteDepartment").
		Str("department_id", id).
		Int("employees_deleted", len(employees)).
		Msg("Department and employees deleted successfully")

	return true, nil
}

// ============================================================================
// Mutation Resolvers - Employee
// ============================================================================

// CreateEmployee is the resolver for the createEmployee field.
func (r *mutationResolver) CreateEmployee(ctx context.Context, input model.CreateEmployeeInput) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "createEmployee").
		Str("name", input.Name).
		Str("email", input.Email).
		Str("department_id", input.DepartmentID).
		Msg("Creating employee")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: employee name is required")
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: employee email is required")
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		log.Error().
			Str("operation", "createEmployee").
			Str("email", input.Email).
			Msg("Validation failed: invalid email format")
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		log.Error().
			Str("operation", "createEmployee").
			Msg("Validation failed: department ID is required")
		return nil, errors.New("department ID is required")
	}

	// Verify department exists
	_, err := r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "createEmployee").
				Str("department_id", input.DepartmentID).
				Msg("Department not found")
			return nil, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "createEmployee").
			Str("department_id", input.DepartmentID).
			Msg("Failed to verify department")
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Create domain model
	emp := &models.Employee{
		ID:           uuid.New().String(),
		Name:         input.Name,
		Email:        input.Email,
		DepartmentID: input.DepartmentID,
	}

	// Save to repository
	if err := r.EmpRepo.Save(emp); err != nil {
		log.Error().
			Err(err).
			Str("operation", "createEmployee").
			Str("employee_id", emp.ID).
			Msg("Failed to save employee")
		return nil, fmt.Errorf("failed to create employee: %w", err)
	}

	log.Info().
		Str("operation", "createEmployee").
		Str("employee_id", emp.ID).
		Str("name", emp.Name).
		Str("email", emp.Email).
		Str("department_id", emp.DepartmentID).
		Msg("Employee created successfully")

	// Convert to GraphQL model
	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// UpdateEmployee is the resolver for the updateEmployee field.
func (r *mutationResolver) UpdateEmployee(ctx context.Context, id string, input model.UpdateEmployeeInput) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "updateEmployee").
		Str("employee_id", id).
		Str("new_name", input.Name).
		Str("new_email", input.Email).
		Str("new_department_id", input.DepartmentID).
		Msg("Updating employee")

	// Validate input
	if input.Name == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: employee name is required")
		return nil, errors.New("employee name is required")
	}
	if input.Email == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: employee email is required")
		return nil, errors.New("employee email is required")
	}
	if !isValidEmail(input.Email) {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Str("email", input.Email).
			Msg("Validation failed: invalid email format")
		return nil, errors.New("invalid email format")
	}
	if input.DepartmentID == "" {
		log.Error().
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Validation failed: department ID is required")
		return nil, errors.New("department ID is required")
	}

	// Check if employee exists
	existing, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "updateEmployee").
				Str("employee_id", id).
				Msg("Employee not found")
			return nil, fmt.Errorf("employee not found")
		}
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	// Verify department exists
	_, err = r.DeptRepo.FindByID(input.DepartmentID)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "updateEmployee").
				Str("employee_id", id).
				Str("department_id", input.DepartmentID).
				Msg("Department not found")
			return nil, fmt.Errorf("department not found")
		}
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Str("department_id", input.DepartmentID).
			Msg("Failed to verify department")
		return nil, fmt.Errorf("failed to verify department: %w", err)
	}

	// Update domain model
	existing.Name = input.Name
	existing.Email = input.Email
	existing.DepartmentID = input.DepartmentID

	// Save to repository
	if err := r.EmpRepo.Update(existing); err != nil {
		log.Error().
			Err(err).
			Str("operation", "updateEmployee").
			Str("employee_id", id).
			Msg("Failed to update employee")
		return nil, fmt.Errorf("failed to update employee: %w", err)
	}

	log.Info().
		Str("operation", "updateEmployee").
		Str("employee_id", existing.ID).
		Str("name", existing.Name).
		Str("email", existing.Email).
		Str("department_id", existing.DepartmentID).
		Msg("Employee updated successfully")

	// Convert to GraphQL model
	return &model.Employee{
		ID:           existing.ID,
		Name:         existing.Name,
		Email:        existing.Email,
		DepartmentID: existing.DepartmentID,
	}, nil
}

// DeleteEmployee is the resolver for the deleteEmployee field.
func (r *mutationResolver) DeleteEmployee(ctx context.Context, id string) (bool, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "deleteEmployee").
		Str("employee_id", id).
		Msg("Deleting employee")

	// Check if employee exists
	_, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Warn().
				Str("operation", "deleteEmployee").
				Str("employee_id", id).
				Msg("Employee not found")
			return false, fmt.Errorf("employee not found")
		}
		log.Error().
			Err(err).
			Str("operation", "deleteEmployee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return false, fmt.Errorf("failed to find employee: %w", err)
	}

	// Delete the employee
	if err := r.EmpRepo.Delete(id); err != nil {
		log.Error().
			Err(err).
			Str("operation", "deleteEmployee").
			Str("employee_id", id).
			Msg("Failed to delete employee")
		return false, fmt.Errorf("failed to delete employee: %w", err)
	}

	log.Info().
		Str("operation", "deleteEmployee").
		Str("employee_id", id).
		Msg("Employee deleted successfully")

	return true, nil
}

// ============================================================================
// Query Resolvers - Department
// ============================================================================

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context, id string) (*model.Department, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "department").
		Str("department_id", id).
		Msg("Fetching department")

	dept, err := r.DeptRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Debug().
				Str("operation", "department").
				Str("department_id", id).
				Msg("Department not found")
			return nil, nil // GraphQL convention: return nil for not found
		}
		log.Error().
			Err(err).
			Str("operation", "department").
			Str("department_id", id).
			Msg("Failed to find department")
		return nil, fmt.Errorf("failed to find department: %w", err)
	}

	log.Debug().
		Str("operation", "department").
		Str("department_id", dept.ID).
		Str("name", dept.Name).
		Msg("Department found")

	return &model.Department{
		ID:   dept.ID,
		Name: dept.Name,
	}, nil
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "departments").
		Msg("Fetching all departments")

	depts, err := r.DeptRepo.FindAll()
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "departments").
			Msg("Failed to fetch departments")
		return nil, fmt.Errorf("failed to fetch departments: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Department, len(depts))
	for i, dept := range depts {
		result[i] = &model.Department{
			ID:   dept.ID,
			Name: dept.Name,
		}
	}

	log.Debug().
		Str("operation", "departments").
		Int("count", len(result)).
		Msg("Departments fetched successfully")

	return result, nil
}

// ============================================================================
// Query Resolvers - Employee
// ============================================================================

// Employee is the resolver for the employee field.
func (r *queryResolver) Employee(ctx context.Context, id string) (*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employee").
		Str("employee_id", id).
		Msg("Fetching employee")

	emp, err := r.EmpRepo.FindByID(id)
	if err != nil {
		if errors.Is(err, models.ErrNotFound) {
			log.Debug().
				Str("operation", "employee").
				Str("employee_id", id).
				Msg("Employee not found")
			return nil, nil // GraphQL convention: return nil for not found
		}
		log.Error().
			Err(err).
			Str("operation", "employee").
			Str("employee_id", id).
			Msg("Failed to find employee")
		return nil, fmt.Errorf("failed to find employee: %w", err)
	}

	log.Debug().
		Str("operation", "employee").
		Str("employee_id", emp.ID).
		Str("name", emp.Name).
		Msg("Employee found")

	return &model.Employee{
		ID:           emp.ID,
		Name:         emp.Name,
		Email:        emp.Email,
		DepartmentID: emp.DepartmentID,
	}, nil
}

// Employees is the resolver for the employees field.
func (r *queryResolver) Employees(ctx context.Context) ([]*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employees").
		Msg("Fetching all employees")

	emps, err := r.EmpRepo.FindAll()
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "employees").
			Msg("Failed to fetch employees")
		return nil, fmt.Errorf("failed to fetch employees: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	log.Debug().
		Str("operation", "employees").
		Int("count", len(result)).
		Msg("Employees fetched successfully")

	return result, nil
}

// EmployeesByDepartment is the resolver for the employeesByDepartment field.
func (r *queryResolver) EmployeesByDepartment(ctx context.Context, departmentID string) ([]*model.Employee, error) {
	// Get logger with request ID
	requestID := middleware.GetRequestID(ctx)
	log := logger.WithRequestID(requestID)

	log.Info().
		Str("operation", "employeesByDepartment").
		Str("department_id", departmentID).
		Msg("Fetching employees by department")

	emps, err := r.EmpRepo.FindByDepartmentID(departmentID)
	if err != nil {
		log.Error().
			Err(err).
			Str("operation", "employeesByDepartment").
			Str("department_id", departmentID).
			Msg("Failed to fetch employees by department")
		return nil, fmt.Errorf("failed to fetch employees by department: %w", err)
	}

	// Convert to GraphQL models
	result := make([]*model.Employee, len(emps))
	for i, emp := range emps {
		result[i] = &model.Employee{
			ID:           emp.ID,
			Name:         emp.Name,
			Email:        emp.Email,
			DepartmentID: emp.DepartmentID,
		}
	}

	log.Debug().
		Str("operation", "employeesByDepartment").
		Str("department_id", departmentID).
		Int("count", len(result)).
		Msg("Employees fetched successfully")

	return result, nil
}

// ============================================================================
// Query Resolvers - Health Check
// ============================================================================

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// ============================================================================
// Helper Functions
// ============================================================================

// isValidEmail validates email format
func isValidEmail(email string) bool {
	emailRegex := regexp.MustCompile(`^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$`)
	return emailRegex.MatchString(email)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
